/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.92
 * Generated at: 2023-10-15 12:43:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import classes.Conexao;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;

public final class listaCao_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("classes.Conexao");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"width=device-width; initial-scale=1.0\" charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"./assets/css/lista.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"./assets/css/reset.css\"/>\n");
      out.write("        <style>\n");
      out.write("            .sem-cachorro{\n");
      out.write("                background-color: #FFF;\n");
      out.write("                padding: 20px;\n");
      out.write("                margin: 0 auto;\n");
      out.write("                width: 80%;\n");
      out.write("                height: 60%;\n");
      out.write("                border-radius: 30px;\n");
      out.write("            }\n");
      out.write("            .img-sem-cachorro{\n");
      out.write("                width: 65%;\n");
      out.write("                margin: 15px 0;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        <title>Dogspace - Cães</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h1 id=\"title-lista\">Lista de Cachorros</h1>\n");
      out.write("        ");

            Conexao conexao = new Conexao();
            Connection con = conexao.abreConec();
            PreparedStatement st;

            try {
                st = con.prepareStatement("select distinct raca from animal");
                ResultSet rs = st.executeQuery();
                if(!rs.isBeforeFirst()){
                    
      out.write("\n");
      out.write("                        <div class=\"sem-cachorro\">\n");
      out.write("                            <h2>Nenhum Cachorro Cadastrado</h2>\n");
      out.write("                            <img class=\"img-sem-cachorro\" src=\"./assets/img/dog-desastrado.png\">\n");
      out.write("                        </div>\n");
      out.write("                    ");

                }
                while (rs.next()) {
                    String racaAtual = rs.getString("raca");
                    
      out.write("\n");
      out.write("                        <div class=\"campo-raca read\">\n");
      out.write("                        <div class=\"topo-campo\">\n");
      out.write("                            <span class=\"nome-raca\">");
      out.print( racaAtual);
      out.write("</span>\n");
      out.write("                            <div class=\"img\" style=\"background-image: url('./assets/img/");
      out.print( racaAtual);
      out.write(".png')\"></div>\n");
      out.write("                        </div>\n");
      out.write("                    ");

                    try {
                        st = con.prepareStatement("select * from animal where raca = '"+racaAtual+"'");
                        ResultSet r = st.executeQuery();
                        while (r.next()) {
                            
      out.write("\n");
      out.write("                                <div class=\"cao\">\n");
      out.write("                                    <span class=\"id-cao\">ID: ");
      out.print( r.getString("id"));
      out.write("</span>\n");
      out.write("                                    <span class=\"nome-cao\">Nome: ");
      out.print( r.getString("nome"));
      out.write("</span>\n");
      out.write("                                    <span class=\"sexo-cao\">Sexo: ");
      out.print( r.getString("sexo"));
      out.write("</span>\n");
      out.write("                                    <span class=\"idade-cao\">Idade: ");
      out.print( r.getString("idade"));
      out.write("</span>\n");
      out.write("                                    <span class=\"peso-cao\">Peso: ");
      out.print( r.getString("peso"));
      out.write(" kg</span>\n");
      out.write("                                    <span class=\"cao-btn excluir\"><a href=\"excPet.jsp?cod=");
      out.print(r.getString("id"));
      out.write("\">Excluir</a></span>\n");
      out.write("                                </div>\n");
      out.write("                            ");

                        }
                    } catch (Exception ex) {
                        out.print("Erro: " + ex.getMessage());
                    }
                    
      out.write("\n");
      out.write("                        </div>  \n");
      out.write("                    ");

                }
            } catch (Exception ex) {
                out.print("Erro: " + ex.getMessage());
            }


            
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
